# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - devops-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzurePowerShell@4
  inputs:
    azureSubscription: '92388c65-7bea-417c-afc3-568a78329c7a'
    azurePowerShellVersion: latestVersion
    scriptType: inlineScript
    inline: |
      foreach($file in Get-ChildItem "data-factory-resources/pipeline") {
        Write-Host "Deploying $($file.Basename)"
        Set-AzDataFactoryV2Pipeline -Force `
          -ResourceGroupName "project01rfuster-rg" `
          -DataFactoryName "project01rfusteradfprd" `
          -Name "$($file.Basename)" `
          -File "$($file.FullName)"
      }